name: Release python package

on:
  push:
    tags:
      - "*"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install uv
        uses: astral-sh/setup-uv@v1

      - name: Install project
        run: uv pip install .

      - name: Set version from tag
        run: uvx hatch version "${{ github.ref_name }}"

      - name: Build artifacts
        run: uv build

      - name: Publish package
        env:
          UV_PUBLISH_TOKEN: ${{ secrets.PYPI_TOKEN }}
        run: uv publish --token "${{ secrets.PYPI_TOKEN }}"
