name: Release python package

on:
  release:
    types:
      - released

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Install uv with python
        uses: astral-sh/setup-uv@v7
        with:
          python-version: "3.12"
          enable-cache: true

      - name: Set version from tag
        run: uv version "${{ github.ref_name }}"

      - name: Build artifacts
        run: uv build

      - name: Publish package
        run: uv publish --token "${{ secrets.PYPI_TOKEN }}"
