name: Testing package

on:
  pull_request:
    paths-ignore:
      - '*.md'
  push:
    paths-ignore:
      - '*.md'


jobs:
  lint:
    strategy:
      matrix:
        cmd: ["black", "mypy", "ruff"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5


      - name: Install uv with python
        uses: astral-sh/setup-uv@v7
        with:
          python-version: "3.12"
          enable-cache: true


      - name: Install dependencies
        run: uv sync --all-extras

      - name: Run lint check
        run: uv run pre-commit run -a ${{ matrix.cmd }}
