name: Testing package

on:
  - push
  - pull_request

jobs:
  lint:
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]
        cmd: ["black", "mypy", "ruff"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install uv
        uses: astral-sh/setup-uv@v1

      - name: Cache uv dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/uv
          key: >-
            ${{ runner.os }}-uv-${{ matrix.python-version }}-${{ hashFiles('pyproject.toml') }}

      - name: Install dependencies
        run: uv pip install ".[dev]"

      - name: Run lint check
        run: uv run pre-commit run -a ${{ matrix.cmd }}
